version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=testapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=helloworld
    expose:
      - "3309"
    ports:
      - "3309:3306"
    restart: always
    volumes:
      - /data/mysql
  spring-boot-jpa-app:
    image: assignment/spring-boot-producer
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app